### ISSUE TITLE
ot-ctl router table loses some information while printing output on the console

### ISSUE THREAD

**Issue by vijayrao1988** [openthread/ot-br-posix#497]
**Description**
There are formatting issues in the output from ot-ctl when it prints out the router table. These seem to be consistent on occasions, but random on some.

**To Reproduce**
1. Form a Thread network with one of the devices on the network being a ot-br.
2. Call ot-ctl to print out the router table as follows:
`sudo ot-ctl router table`
3. The output seems malformed. For instance:
`up-b@upb:~$ sudo ot-ctl router table`
`[sudo] password for up-b: `
`| ID | RLOC16 | Next Hop | Path Cost | LQ In | LQ Out | Age | Extended MAC     |`
`+----+--------+----------+-----------+-------+--------+-----+------------------+`
`|  4 | 0x1000 |       37 |         1 |     3 |      2 |   7 | 16cbad26abdbfdc0 |`
`000 |       37 |         1 |     2 |      0 |   1 | feef1925204c4d30 |`
`| 19 | 0x4c00 |       37 |         1 |     3 |      1 |  22 | b7b6a641541bdc08 |`
`| 21 | 0x5400 |       37 |         1 |     0 |      0 |  32 | b3cd5abed47b2495 |`
`  37 |         1 |     3 |      3 |   7 | 9b8d5176362eada3 |`
`| 37 | 0x9400 |       34 |         1 |     3 |      3 |  21 | 2635716229c9da5e |`
`| 42 | 0xa800 |       37 |         1 |     0 |      0 |   6 | 4bfb977d3258aaf1 |`
`     0 |     0 |      0 |   0 | 0000000000000000 |`

`Done`

I have been able to reproduce this issue on both attempts I could do using 2 different machines. I shall try and deploy more networks and to check for more situations.

**Expected behavior**
The table should be clearly formatted without missing pieces of information

**Comment by gjc13** [comment]
This bug has been fixed in the latest OpenThread. Just verified with an old ot-ctl binary and the cutting-edge building from OpenThread master.

Old binary
```
# gjc @ gjc in ~/src/openthread/build on git:9e291e62e x [10:14:57] 
$ sudo ot-ctl router table
| ID | RLOC16 | Next Hop | Path Cost | LQ In | LQ Out | Age | Extended MAC     |
+----+--------+----------+-----------+-------+--------+-----+------------------+
| 18 | 0x4800 |       54 |         1 |     3 |      3 |   5 | 1eb7bb288dbde1ff |
| 19 | 0x4c00 |       18 |         1 |     3 |      3 |   5 | 260a78790d5f95c0 |
000 |       63 |         0 |     0 |      0 |   0 | de7b696b6768fe05 |
| 54 | 0xd800 |       18 |         1 |     3 |      3 |   4 | 7edeebd672fd1262 |

Done
```

Cutting edge build
```
# gjc @ gjc in ~/src/openthread/build on git:9e291e62e x [10:14:49] 
$ sudo ./src/posix/ot-ctl router table
| ID | RLOC16 | Next Hop | Path Cost | LQ In | LQ Out | Age | Extended MAC     |
+----+--------+----------+-----------+-------+--------+-----+------------------+
| 18 | 0x4800 |       54 |         1 |     3 |      3 |  15 | 1eb7bb288dbde1ff |
| 19 | 0x4c00 |       18 |         1 |     3 |      3 |  18 | 260a78790d5f95c0 |
| 48 | 0xc000 |       63 |         0 |     0 |      0 |   0 | de7b696b6768fe05 |
| 54 | 0xd800 |       18 |         1 |     3 |      3 |  19 | 7edeebd672fd1262 |

Done

```

**Comment by vijayrao1988** [comment]
Does that mean this is yet to be implemented in the OpenThread Border Router package?

Because from your snippet, the instance of <ot-ctl>, installed as part of ot-br, still produces the same buggy format but the binary built from the OpenThread source code works fine.

**Comment by gjc13** [comment]
> Does that mean this is yet to be implemented in the OpenThread Border Router package?
> 
> Because from your snippet, the instance of ot-ctl, installed as part of ot-br, still produces the same buggy format but the binary built from the OpenThread source code works fine.

The openthread in the code base has just been updated in https://github.com/openthread/ot-br-posix/pull/495. Rebuilding and re-installing will resolve this issue. My `ot-ctl` under the system path is quite outdated.

**Comment by vijayrao1988** [comment]
So a **git fetch** in the ot-br-posix repository, followed by **bootstrap** and **setup** should do it? Or would a separate download and build of the main openthread repository be required?

Secondly, I have observed that **ot-ctl router table** now freezes before and never completes. Attaching a screenshot to show this.
<img width="491" alt="Screenshot 2020-07-04 at 3 35 45 PM" src="https://user-images.githubusercontent.com/4222604/86514781-2fdb2f00-be0c-11ea-8186-a5fa87adbf88.png">

Also some of the routers show an Extended MAC of 0000000000000000. Why would this be? Will this also get resolved in the updated ot-ctl?

**Comment by vijayrao1988** [comment]
Updated to the latest ot-br-posix code base. The ot-ctl router table output is much better now but it still gets stuck before finishing.

![Screenshot 2020-07-06 at 5 55 34 PM](https://user-images.githubusercontent.com/4222604/86619367-58049280-bfb2-11ea-8fd0-faa09cfca04e.png)

**Comment by jwhui** [comment]
The openthread/ot-br-posix repo pulls in the openthread/openthread repo
using git submodule.

To grab the latest, you should use `git submodule update --recursive
--depth 1`

--
Jonathan Hui

**Comment by jwhui** [comment]
The default CLI output buffer size is configured via
OPENTHREAD_CONFIG_CLI_UART_TX_BUFFER_SIZE
<https://github.com/openthread/openthread/blob/203774c1811c2b0589ffa67b9664060c5b8dd1b1/src/cli/cli_config.h#L65>
and
is currently 1024 bytes.

Can you try increasing that to something larger?

--
Jonathan Hui

**Comment by jwhui** [comment]
Closing stale issue.

**Comment by vijayrao1988** [comment]
Sorry to ask another question on this closed issue. From what you suggest, the solution lies in modifying the firmware of the RCP and not anything with the otbr itself?

**Comment by jwhui** [comment]
> Sorry to ask another question on this closed issue. From what you suggest, the solution lies in modifying the firmware of the RCP and not anything with the otbr itself?

@vijayrao1988 , the `OPENTHREAD_CONFIG_CLI_UART_TX_BUFFER_SIZE ` config option applies to the OpenThread process that runs on the RPi and should not require any affect your RCP firmware.

**Comment by vijayrao1988** [comment]
Next hop information seems to be incorrect, as does the LQ In and LQ Out. Is there a flag that can be checked for reliability of this output.

![Screenshot 2020-10-15 at 09 58 22](https://user-images.githubusercontent.com/4222604/96101075-f7e48d00-0ecc-11eb-8ddc-408042dd84f5.png)

**Comment by vijayrao1988** [comment]
> The openthread/ot-br-posix repo pulls in the openthread/openthread repo using git submodule. To grab the latest, you should use `git submodule update --recursive --depth 1`
> […](#)

This returns back with seemingly no effect.

<img width="579" alt="Screenshot 2020-10-15 at 10 20 14" src="https://user-images.githubusercontent.com/4222604/96103792-05e7dd00-0ed0-11eb-83a8-7e58cc969e06.png">

**Comment by jwhui** [comment]
> > The openthread/ot-br-posix repo pulls in the openthread/openthread repo using git submodule. To grab the latest, you should use `git submodule update --recursive --depth 1`
> > […](#)
> 
> This returns back with seemingly no effect.
> 
> <img alt="Screenshot 2020-10-15 at 10 20 14" width="579" src="https://user-images.githubusercontent.com/4222604/96103792-05e7dd00-0ed0-11eb-83a8-7e58cc969e06.png">

If no output, then your submodule is already consistent with the git commit hash that it is pointing to. You can check the submodule status by using `git submodule status`.

Also remember to fetch updates from the upstream repo, where the updates may change the git commit of a given submodule.

**Comment by jwhui** [comment]
> Next hop information seems to be incorrect, as does the LQ In and LQ Out. Is there a flag that can be checked for reliability of this output?
> 
> ![Screenshot 2020-10-15 at 09 58 22](https://user-images.githubusercontent.com/4222604/96101075-f7e48d00-0ecc-11eb-8ddc-408042dd84f5.png)

It appears that your device is not able to establish neighbor links.
- A Next Hop of 63 indicates that there is no valid route to the given device.
- A LQ In and LQ Out of zero indicates that there is no direct link established to the given device.

Can you provide more information on your setup?
- Are you using physical devices or simulation?
- If physical, what hardware are you using?
- Can you provide the output of `git submodule status`?

**Comment by vijayrao1988** [comment]
We are using physical devices. These are deployed in an area of 250m x 250m in an urban area. We are using a custom board built using the Silicon Labs MGM12P321024GA. This is very similar to BRD4304A. It might be worth mentioning that these devices run the Silicon Labs Thread implementation, while the output I am posting is from a OpenThread RCP attached to a Ubuntu 64-bit Border Router.

Additionally, I am able to ping all these devices on the mesh network.
```console
parser-gt1@parsergt1:~$ ping -r -I wpan0 -t 64 -c 2 ff03::1
PING ff03::1(ff03::1) from fde6:4cd3:a4e0:1:0:ff:fe00:4c22 wpan0: 56 data bytes
64 bytes from fde6:4cd3:a4e0:1:dad4:aa89:eea1:adc5: icmp_seq=1 ttl=64 time=228 ms
64 bytes from fde6:4cd3:a4e0:1:f3c3:b04e:2f00:ba04: icmp_seq=1 ttl=64 time=501 ms (DUP!)
64 bytes from fde6:4cd3:a4e0:1:2b7b:581c:c88a:bb40: icmp_seq=1 ttl=64 time=556 ms (DUP!)
64 bytes from fde6:4cd3:a4e0:1:9e45:97b2:d9cd:9897: icmp_seq=1 ttl=64 time=568 ms (DUP!)
64 bytes from fde6:4cd3:a4e0:1:c663:eafc:1ef9:3435: icmp_seq=1 ttl=64 time=579 ms (DUP!)
64 bytes from fde6:4cd3:a4e0:1:ae0e:4e7a:4888:54c9: icmp_seq=1 ttl=64 time=596 ms (DUP!)
64 bytes from fde6:4cd3:a4e0:1:524e:5922:d691:a3b9: icmp_seq=1 ttl=64 time=618 ms (DUP!)
64 bytes from fde6:4cd3:a4e0:1:6791:2be6:d3b:8cc0: icmp_seq=1 ttl=64 time=651 ms (DUP!)
64 bytes from fde6:4cd3:a4e0:1:2b32:bc0a:5ed8:972a: icmp_seq=1 ttl=64 time=674 ms (DUP!)
64 bytes from fde6:4cd3:a4e0:1:92f6:df76:c777:94bc: icmp_seq=1 ttl=64 time=685 ms (DUP!)
64 bytes from fde6:4cd3:a4e0:1:f2a:85a8:4a98:195a: icmp_seq=1 ttl=64 time=725 ms (DUP!)
64 bytes from fde6:4cd3:a4e0:1:b788:f571:e548:f591: icmp_seq=1 ttl=64 time=736 ms (DUP!)
64 bytes from fde6:4cd3:a4e0:1:3a8e:88e1:1aae:f357: icmp_seq=1 ttl=64 time=749 ms (DUP!)
64 bytes from fde6:4cd3:a4e0:1:f78e:71b7:c7c3:d760: icmp_seq=1 ttl=64 time=763 ms (DUP!)
64 bytes from fde6:4cd3:a4e0:1:4a8e:6d2a:3dc2:576a: icmp_seq=1 ttl=64 time=807 ms (DUP!)
64 bytes from fde6:4cd3:a4e0:1:be58:48a2:4afb:ae5e: icmp_seq=1 ttl=64 time=816 ms (DUP!)
64 bytes from fde6:4cd3:a4e0:1:3aa3:830e:9a48:393d: icmp_seq=1 ttl=64 time=857 ms (DUP!)
64 bytes from fde6:4cd3:a4e0:1:be58:48a2:4afb:ae5e: icmp_seq=1 ttl=64 time=912 ms (DUP!)
64 bytes from fde6:4cd3:a4e0:1:a4b:7d10:3b4c:7496: icmp_seq=1 ttl=64 time=921 ms (DUP!)
64 bytes from fde6:4cd3:a4e0:1:5664:b29e:cfa4:abfc: icmp_seq=1 ttl=64 time=935 ms (DUP!)
64 bytes from fde6:4cd3:a4e0:1:73c6:15e:df72:a0aa: icmp_seq=1 ttl=64 time=958 ms (DUP!)
64 bytes from fde6:4cd3:a4e0:1:1bad:b390:5d94:3ce1: icmp_seq=1 ttl=64 time=995 ms (DUP!)
64 bytes from fde6:4cd3:a4e0:1:2aad:56d7:4266:101c: icmp_seq=1 ttl=64 time=1009 ms (DUP!)
64 bytes from fde6:4cd3:a4e0:1:dad4:aa89:eea1:adc5: icmp_seq=2 ttl=64 time=234 ms

--- ff03::1 ping statistics ---
2 packets transmitted, 2 received, +22 duplicates, 0% packet loss, time 999ms
rtt min/avg/max/mdev = 228.220/711.309/1009.203/204.694 ms, pipe 2
```

I have seen issues with running newer versions of OpenThread and the Border Router and have stuck with a stable version from June 2020.

```console
parser-gt1@parsergt1:~/ot-br-posix$ git submodule status
 6e80c8b058f57806e7abbc6bd88f300825f8963a third_party/openthread/repo (6e80c8b)
```

**Comment by jwhui** [comment]
@vijayrao1988 It is odd that the route table shows no routes/links but you are able to communicate with devices.

Do you experience the same behavior when only a few devices are active? Are you able to provide a pcap file from a sniffer capture?

**Comment by vijayrao1988** [comment]
Yes, we experience the same issue with smaller networks where route table has no Next Hop information. The other odd thing is that ot-ctl networkdiagnostic is able to retrieve all network information.

We had Next Hop information earlier with the same version of ot-br-posix though.

Here are 2 pcap files captured during:

1. normal operation
2. router table query and some other router queries
[PacketCaptures.zip](https://github.com/openthread/ot-br-posix/files/5394233/PacketCaptures.zip)

**Comment by jwhui** [comment]
@vijayrao1988 , can you tell whether the devices in the router table are actually operating in the router role? Can you also provide the child table output? I'm wondering if the devices were routers at one point then dropped back to the child role.
